### ISSUE TITLE
Expose `GenerationId` for consumed messages

### ISSUE THREAD

**Issue by kerinin** [bsm/sarama-cluster#114] opened 2017-03-04 14:01 UTC
I'm working on a consumer that needs to have a consistent view of partition ownership across consumers, which I think requires knowing the group `GenerationId` for each message.  

Specifically, my consumer needs to guarantee that that message handling is mutually exclusive across consumers.  This should be true for a given message so long as the local consumer delays processing a newly-acquired partition for `Group.Session.Timeout` and has successfully issued a heartbeat within the past `Group.Session.Timeout` before processing a given message.

This seems to require conflicting uses of `Notifications()` and `Messages()`.  On the one hand, it's necessary to consume `Notifications()` independently of `Messages()` so the message handler can be notified of partition releases that happen after reading a message but before the operation requiring mutual-exclusivity.  On the other hand acquisitions, reads and releases need to be serialized to ensure that a given message is consumed after the correct delay period.  For instance, consider the following sequence:

1. Partition `N` is acquired by process `P1`, message `M1` is read, partition `N` is released
2. Partition `N` is acquired by process `P2`, message `M2` is read, partition `N` is released
3. Partition `N` is acquried by process `P1` again, message `M3` is read.

In this case, `P1` could see either `[acquire N, M1, M3, release N, acquire N]` or `[acquire N, M1, release N, acquire N, M3]`.  In the first case `M3` potentially gets processed immediately, conflicting with writes by `P2`.

I think the best solution here is to expose `GenerationId` from the [sarama.JoinGroupResponse](https://godoc.org/github.com/Shopify/sarama#JoinGroupResponse).  This would allow `Messages()` consumers to differentiate between messages received from different "lease" periods.  The bad news is I think this requires changing the method signature of `Messages()` to use a wrapper around `sarama.ConsumerMessage`. Maybe there's another way?

**Comment by kerinin** [comment] 2017-03-04 15:08
Thinking about this more, there's a similar situation with partition release.  When a partition release notification is received, I don't think there's currently a way to know when all messages for a given partition have been consumed. 

Does it make sense for `sarama-cluster.Consumer` to expose `Messages()`? Maybe it would be better to restrict the API to group management, and use the existing sarama tools for message fetching and offset management?

**Comment by dim** [comment] 2017-03-06 09:34
Sorry, but could you please give me a more specific example or use case of what you are trying to achieve? So far, from your description, I take that you are trying to change Kafka's default delivery guarantee from "at-least-once" to "exactly-once", right?

Sarama cluster does its best to prevent a message from being consumed 2x but it generally follows the Kafka principle of "at-least-once". The `Notifications` channel is not supposed to be used operationally it's for information and logging at best. Synchronising the consumption of `Notifications` and `Messages`  channels would only help your cause if you are consuming messages within the same process, but there is no way to assert "exactly-once" if your consumers are distributed across multiple processes/hosts (as intended). 

Internally, we have built highly transactional systems that implement de-duping on top of Kafka, which requires a central store to maintain state (e.g. memcached or redis). This - obviously - adds significant overhead but I cannot really tell you if it's an appropriate solution without knowing your particular use case.

**Comment by dim** [comment] 2017-03-13 12:08
Closing for now ...

**Closed by dim** 2017-03-13 12:08 UTC
