### ISSUE TITLE
panic: close of closed channel

### ISSUE THREAD

**Issue by jdness** [bsm/sarama-cluster#20] opened 2016-01-22 20:25 UTC
Yesterday we upgraded to Kafka 0.9 and the latest Sarama library. We are using sarama-cluster to distribute/rebalance our four kafka running instances. This morning, two of our four daemon instances crashed with "panic: close of closed channel". I haven't been able to reproduce it yet but here is what I see in the logs:

[Sarama] 2016/01/22 07:47:29 client/metadata fetching metadata for all topics from broker localhost:9092
[Sarama] 2016/01/22 07:49:03 cluster/consumer -a9899ac7-1b49-40cf-848d-bb843b7231d7 rebalance
2016/01/22 07:49:03 kafka server: The provided member is not known in the current generation.
[Sarama] 2016/01/22 07:49:03 client/coordinator requesting coordinator for consumergoup backend from localhost:9092
[Sarama] 2016/01/22 07:49:03 client/coordinator coordinator for consumergoup backend is #0 (services.veramine.com:9092)
[Sarama] 2016/01/22 07:49:03 consumer/broker/2 disconnecting due to error processing FetchRequest: read tcp 192.168.10.4:54970->192.168.10.4:9094: i/o timeout
[Sarama] 2016/01/22 07:49:03 Closed connection to broker services.veramine.com:9094
2016/01/22 07:49:03 kafka: 1 errors while consuming
[Sarama] 2016/01/22 07:49:03 cluster/consumer -a9899ac7-1b49-40cf-848d-bb843b7231d7 rebalance
[Sarama] 2016/01/22 07:49:03 client/coordinator requesting coordinator for consumergoup backend from localhost:9092
[Sarama] 2016/01/22 07:49:03 client/coordinator coordinator for consumergoup backend is #0 (services.veramine.com:9092)
panic: close of closed channel

The close came from gopkg.in/bsm/sarama-cluster%2ev2.(*partitionConsumer).Close(0xcb3d2d8d20, 0x0, 0x0)

Here's the code there:

func (c *partitionConsumer) Close() (err error) {
        close(c.dying)
        <-c.dead

        if e := c.pcm.Close(); e != nil {
                err = e
        }
        return
}

Is it possible to first check the partitionConsumer to see if it is already closed before closing, or do you think something needs to be done on sarama side to avoid a panic? I figured that even if a kafka instance died, eventually a rebalance would accomodate that so I'd rather not panic.  Thanks!

Jonathan

**Comment by dim** [comment] 2016-01-23 11:22
Can you please upgrade to the latest version of the library? We have
released a v2 version recently, which is using the new Kafka 0.9 offset
management and rebalancing features.

**Comment by jdness** [comment] 2016-01-23 16:38
Hi Dimitrij, we are using the v2 already, specifically the following:

gopkg.in/bsm/sarama-cluster.v2

We would be happy to pick up any updates that have been merged since then, however.

**Comment by dim** [comment] 2016-01-25 11:19
@jdness sorry, misread the thread earlier, could you please provide a full stack trace?

**Comment by dim** [comment] 2016-01-25 11:48
Actually, I think I got it, should be fixed by #84eed12

**Closed by dim** 2016-01-25 11:48 UTC

**Comment by matbhz** [comment] 2017-04-19 20:33
@jdness did you manage to solve your problem? We recently upgraded to v9.0 and started using Sarama-Cluster, but I get the `The provided member is not known in the current generation` error intermittently. Don't know a way to reproduce though.

**Comment by jdness** [comment] 2017-04-19 20:59
@matbhz yes I do remember this situation.  I believe things improved after we explicitly set the protocol version in the sarama config to the kafka version we were using:

    https://godoc.org/github.com/Shopify/sarama

    var (
        V0_8_2_0  = newKafkaVersion(0, 8, 2, 0)
        V0_8_2_1  = newKafkaVersion(0, 8, 2, 1)
        V0_8_2_2  = newKafkaVersion(0, 8, 2, 2)
        V0_9_0_0  = newKafkaVersion(0, 9, 0, 0)
        V0_9_0_1  = newKafkaVersion(0, 9, 0, 1)
        V0_10_0_0 = newKafkaVersion(0, 10, 0, 0)
        V0_10_0_1 = newKafkaVersion(0, 10, 0, 1)
        V0_10_1_0 = newKafkaVersion(0, 10, 1, 0)
    )

Although we have since switched to using a single Kafka instance limiting the need for automatic rebalancing.

Good luck!

Jonathan

**Comment by matbhz** [comment] 2017-04-20 04:08
@jdness thanks, I have now added V0_9_0_1 during the setup steps for our Kafka Client here.
 
Unfortunately, that didn't, rebalances are happening non-stop :/

**Comment by dim** [comment] 2017-04-20 12:54
@matbhz have you tried Kafka v0.10, do you have the same problem there?

**Comment by dim** [comment] 2017-04-20 13:04
I added 0.9 to the CI matrix and it works just fine: https://travis-ci.org/bsm/sarama-cluster/builds/223945702

You should check your `Config.Group.Session.Timeout` and `Config.Group.Heartbeat.Interval` settings. Here is what the [Kafka Documentation](https://kafka.apache.org/documentation/):

```
heartbeat.interval.ms - The expected time between heartbeats to the group coordinator when using Kafka's group management facilities. Heartbeats are used to ensure that the worker's session stays active and to facilitate rebalancing when new members join or leave the group. The value must be set lower than session.timeout.ms, but typically should be set no higher than 1/3 of that value. It can be adjusted even lower to control the expected time for normal rebalances.

session.timeout.ms - The timeout used to detect worker failures. The worker sends periodic heartbeats to indicate its liveness to the broker. If no heartbeats are received by the broker before the expiration of this session timeout, then the broker will remove the worker from the group and initiate a rebalance. Note that the value must be in the allowable range as configured in the broker configuration by group.min.session.timeout.ms and group.max.session.timeout.ms.
```

**Comment by matbhz** [comment] 2017-04-21 04:25
Hi @dim thanks for the support.
We gave it a try and upgraded to Kafka v0.10.2.0. 

Rebalances are still really frequent. Bumping up the `session.timeout.ms` and `heartbeat.interval.ms` didn't help.

The Kafka Server logs is just spitting this in a loop, because of the rebalances:

```
2017-04-21 04:00:58,193 - INFO  [executor-Heartbeat:Logging@70] - [GroupCoordinator 1]: Stabilized group jobspout generation 138
2017-04-21 04:00:58,195 - INFO  [kafka-request-handler-7:Logging@70] - [GroupCoordinator 1]: Assignment received from leader for group jobspout for generation 138
2017-04-21 04:01:28,177 - INFO  [kafka-request-handler-6:Logging@70] - [GroupCoordinator 1]: Preparing to restabilize group jobspout with old generation 138
2017-04-21 04:01:58,218 - INFO  [executor-Rebalance:Logging@70] - [GroupCoordinator 1]: Stabilized group jobspout generation 139
2017-04-21 04:01:58,295 - INFO  [executor-Heartbeat:Logging@70] - [GroupCoordinator 1]: Preparing to restabilize group jobspout with old generation 139
2017-04-21 04:02:28,225 - INFO  [executor-Heartbeat:Logging@70] - [GroupCoordinator 1]: Group jobspout with generation 140 is now empty
2017-04-21 04:02:58,668 - INFO  [kafka-request-handler-3:Logging@70] - [GroupCoordinator 1]: Preparing to restabilize group jobspout with old generation 140
2017-04-21 04:02:58,668 - INFO  [kafka-request-handler-3:Logging@70] - [GroupCoordinator 1]: Stabilized group jobspout generation 141
2017-04-21 04:02:58,685 - INFO  [kafka-request-handler-3:Logging@70] - [GroupCoordinator 1]: Assignment received from leader for group jobspout for generation 141
2017-04-21 04:03:00,300 - INFO  [kafka-request-handler-6:Logging@70] - [GroupCoordinator 1]: Preparing to restabilize group jobspout with old generation 141
2017-04-21 04:03:30,773 - INFO  [executor-Rebalance:Logging@70] - [GroupCoordinator 1]: Stabilized group jobspout generation 142
2017-04-21 04:03:31,798 - INFO  [executor-Heartbeat:Logging@70] - [GroupCoordinator 1]: Preparing to restabilize group jobspout with old generation 142
...
```
You see, 2~ mins after each `executor-Rebalance`

Now, in debug mode I get a bunch of disconnections -- We're not understanding why though:

```
Mark Poole [3:35 PM] 
```2017-04-20 22:34:45,384 - DEBUG [kafka-network-thread-1-PLAINTEXT-0:RequestChannel$Request@138][] - Completed request:Name: FetchRequest; Version: 0; CorrelationId: 14455; ClientId: beacon; ReplicaId: -1; MaxWait: 250 ms; MinBytes: 1 bytes from connection 10.100.1.75:9092-10.100.5.77:20427;totalTime:250,requestQueueTime:0,localTime:0,remoteTime:250,responseQueueTime:0,sendTime:0,securityProtocol:PLAINTEXT,principal:User:ANONYMOUS
2017-04-20 22:34:45,462 - DEBUG [kafka-network-thread-1-PLAINTEXT-0:RequestChannel$Request@138][] - Completed request:Name: FetchRequest; Version: 0; CorrelationId: 3009; ClientId: thread_events_consumer; ReplicaId: -1; MaxWait: 250 ms; MinBytes: 1 bytes from connection 10.100.1.75:9092-10.100.3.129:20315;totalTime:251,requestQueueTime:0,localTime:0,remoteTime:251,responseQueueTime:0,sendTime:0,securityProtocol:PLAINTEXT,principal:User:ANONYMOUS
2017-04-20 22:34:45,500 - DEBUG [kafka-socket-acceptor-PLAINTEXT-9092:Logging$class@52][] - Accepted connection from /10.100.1.178 on /10.100.1.75:9092. sendBufferSize [actual|requested]: [102400|102400] recvBufferSize [actual|requested]: [102400|102400]
2017-04-20 22:34:45,500 - DEBUG [kafka-network-thread-1-PLAINTEXT-0:Logging$class@52][] - Processor 0 listening to new connection from /10.100.1.178:24368
2017-04-20 22:34:45,501 - DEBUG [kafka-network-thread-1-PLAINTEXT-0:Selector@307][] - Connection with /10.100.1.178 disconnected
java.io.EOFException
        at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:83)
        at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:71)
        at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:153)
        at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:134)
        at org.apache.kafka.common.network.Selector.poll(Selector.java:286)
        at kafka.network.Processor.run(SocketServer.scala:413)
        at java.lang.Thread.run(Thread.java:745)```
```

And the current configurations are:

```
// Producer Setup
	kafkaConfig = cluster.NewConfig()
	kafkaConfig.Consumer.Return.Errors = true

	// Testing
	kafkaConfig.Config.Version = sarama.V0_10_1_0
	kafkaConfig.Group.Heartbeat.Interval = 1 * time.Second
	// ===============================================

	kafkaConfig.Producer.RequiredAcks = sarama.WaitForAll
	kafkaConfig.Producer.Partitioner = ChoosePartitioner
	kafkaConfig.Producer.Return.Successes = true
	kafkaConfig.ClientID = "xyz"

	kafkaConfig.Net.DialTimeout = 30 * time.Second
	kafkaConfig.Net.ReadTimeout = 30 * time.Second
	kafkaConfig.Net.WriteTimeout = 30 * time.Second


	kafkaConfig.Consumer.MaxProcessingTime = 100 * time.Millisecond
```

Any clue? :)

Thanks in advance for your assistance!

**Comment by dim** [comment] 2017-04-21 07:20
It would be interesting to see your server settings. You should also try not to set `kafkaConfig.Group.Heartbeat.Interval` and `kafkaConfig.Consumer.MaxProcessingTime` and leaving them at their defaults instead.

**Comment by matbhz** [comment] 2017-04-21 17:26
@dim that's awesome.

Not setting `kafkaConfig.Consumer.MaxProcessingTime` did the trick (even though the default is also 100ms)
I noticed setting it around 1 sec worked just fine as well! 

I'm intrigued on how it affected rebalances. Guess I am going to dive deeper into Sarama's code and tweak that as necessary.

Thank you so much!

**Comment by dim** [comment] 2017-04-21 18:17
Sarama's default is 250ms. Looks like some of your messages take longer than 100ms to process. Great to hear that it's working
