### ISSUE TITLE
Delivering disordered messages during shutdown(rebalance), causing message loss

### ISSUE THREAD

**Issue by longquanzheng** [bsm/sarama-cluster#255] opened 2018-08-09 23:30 UTC
We are experiencing msg loss during restarting workers, it happens consistently.
But when I added these logs, the message loss disappear.

https://github.com/longquanzheng/sarama-cluster/commit/0c61134e2a0a729345aac2d4fd28bdf2079faf20

I think this is because the logging slow down CommitOffsets() function. There must be some race condition with it.
Do you have any idea?

**Comment by dim** [comment] 2018-08-10 07:38
@longquanzheng I am currently working on implementing cluster functionality into sarama directly - https://github.com/Shopify/sarama/pull/1099. Only a few small bits are missing at this point and I aim to finish those next week.

**Comment by dim** [comment] 2018-08-10 07:40
@longquanzheng I am nevertheless happy to fix the race if you can identify how it happens. We have quite a "fuzzy" test in our suite (see https://github.com/bsm/sarama-cluster/blob/master/consumer_test.go#L284) which seems to pass without losing any messages.

**Comment by dim** [comment] 2018-08-13 09:41
@longquanzheng from what I know, messages are only ordered per topic/partition. also, `Close()` doesn't do anything specific i.e. we are just closing the consumer and waiting for exit. finally, the test I have mentioned above is testing this case, i.e. it starts consumers/shuts them down/starts new ones and no messages are being missed, neither locally nor on the CI. I am not sure how to debug this as this doesn't seem to happen neither to us, nor has it been reported by someone else before.

**Comment by longquanzheng** [comment] 2018-08-14 22:57
@dim we finally found that the bug is here: https://github.com/georgeteo/sarama/commit/9618a792d27f72ba74865bed28f57e6e868baaa9

**Comment by georgeteo** [comment] 2018-08-15 00:27
Actually, the issue is with the sarama/sarama-cluster contract. Specifically, in https://github.com/bsm/sarama-cluster/blob/master/partitions.go#L89, you use `partitonConsumer.Close()`, which will drain the `Messages` channel. 

We use the `PartitionConsumer` abstraction from sarama-cluster, and on `Close` or rebalance, we continue reading from the `Messages` channel, but because Sarama is also reading from that channel, we end up with holes in our stream (e.g., we get msg 100, sarama drain takes msg 101, etc). Then due to a race condition in the shutdown procedure, we may commit msg 102 and lose messages. 

The proposed fix would be to use `AsyncClose` in sarama-cluster `partitions.go:89`.

**Comment by georgeteo** [comment] 2018-08-15 15:35
Thanks for accepting the PR. Can you tag a new release as well?

**Comment by dim** [comment] 2018-08-16 08:33
@georgeteo looks like you didn't run the tests :smile:

**Comment by danpmx** [comment] 2018-08-16 14:18
I've tried this fix today and reverted back.
Looks like something is wrong
when listening to Notifications channel, I receive infinite rebalance error messages

**Comment by jpiper** [comment] 2018-08-16 15:55
By the way #258 worked for me with `kafkaConfig.Group.Mode = cluster.ConsumerModePartitions` it was only in the default mode that crashed for me

**Comment by georgeteo** [comment] 2018-08-17 17:28
@danpmx, @jpiper, I'm unable to reproduce the crash. Can you post your consumer configuration?

When running the following non partition consumer code, I don't see either crashing or infinite rebalance:
```
func main() {
	config := cluster.NewConfig()
	config.Group.Return.Notifications = true
	config.Consumer.Return.Errors = true
	config.Consumer.Offsets.Initial = sarama.OffsetOldest
	consumer, err := cluster.NewConsumer([]string{"localhost:9092"}, "cg", []string{"test01"}, config)
	if err != nil {
		log.Fatal("unable to start consumer", err)
	}

	for {
		select {
		case msg, ok := <- consumer.Messages():
			if !ok {
				log.Println("ERROR: message channel is closed")
				continue
			}
			log.Printf("INFO: received offset %d from %s-%d\n", msg.Offset, msg.Topic, msg.Partition)
		case err, ok := <- consumer.Errors():
			if !ok {
				log.Println("ERROR: consumer channel is closed")
				continue
			}
			log.Printf("INFO: received error %s from sarama-cluster", err.Error())
		case ntf, ok := <- consumer.Notifications():
			if !ok {
				log.Println("ERROR: notification channel is closed")
				continue
			}
			log.Printf("INFO: received notification %s from sarama-cluster", ntf.Type.String())
		}
	}
}
```

# Two consumer workers:
## Worker 1
```
 ./sarama-test
2018/08/17 10:22:43 INFO: received notification rebalance start from sarama-cluster
2018/08/17 10:22:47 INFO: received notification rebalance OK from sarama-cluster
2018/08/17 10:22:48 INFO: received offset 19 from test01-0
2018/08/17 10:22:48 INFO: received offset 20 from test01-0
2018/08/17 10:22:48 INFO: received offset 21 from test01-0
# Worker 2 join here
2018/08/17 10:22:51 INFO: received notification rebalance start from sarama-cluster
2018/08/17 10:22:51 INFO: received notification rebalance OK from sarama-cluster
2018/08/17 10:23:00 INFO: received offset 22 from test01-0
2018/08/17 10:23:02 INFO: received offset 23 from test01-0
2018/08/17 10:23:03 INFO: received offset 24 from test01-0
2018/08/17 10:23:04 INFO: received offset 25 from test01-0
# Worker 2 leave here. 
2018/08/17 10:23:12 INFO: received notification rebalance start from sarama-cluster
# Worker 1 leaves. 
```

## Worker 2
```
# worker 1 leaves
./sarama-test
2018/08/17 10:23:10 INFO: received notification rebalance start from sarama-cluster
2018/08/17 10:24:06 INFO: received notification rebalance error from sarama-cluster
2018/08/17 10:24:06 INFO: received notification rebalance start from sarama-cluster
2018/08/17 10:24:09 INFO: received notification rebalance OK from sarama-cluster
2018/08/17 10:24:09 INFO: received offset 26 from test01-0
2018/08/17 10:24:09 INFO: received offset 27 from test01-0
2018/08/17 10:24:09 INFO: received offset 28 from test01-0
2018/08/17 10:24:09 INFO: received offset 29 from test01-0
2018/08/17 10:24:27 INFO: received notification rebalance start from sarama-cluster
2018/08/17 10:24:27 INFO: received notification rebalance OK from sarama-cluster
```

@dim: do you have any clues why non partition consumer might be broken with my recent change?

**Comment by jpiper** [comment] 2018-08-17 19:27
@georgeteo  I’m using this config
```go
kafkaConfig := cluster.NewConfig()
sarama.MaxResponseSize = 104857600
sarama.MaxRequestSize = 104857600

kafkaConfig.Version = sarama.V1_1_0_0 // Sarama will default to 0.8
kafkaConfig.Group.PartitionStrategy = cluster.StrategyRoundRobin
kafkaConfig.Consumer.Return.Errors = true
kafkaConfig.Group.Return.Notifications = true
kafkaConfig.ChannelBufferSize = 1000
```

**Comment by venkat1109** [comment] 2018-08-17 19:34
I am able to repro behavior identical to what @danpmx reported. I digged into this and the root cause appears to be a deadlock in the underlying sarama library (which existed even before the fix added by george). But the new fix caused this deadlock to manifest itself differently i.e. after the fix, its a bunch of rebalance errors; before the fix, the deadlock will lead to consumer not receiving any messages at all. Following is the potential bug I discovered:

- Setup
  - Topic with two partitions
  - Each partition has about 10k messages
  - partition ChannelBufferSize=32, dwellTimer=1s and maxProcessingTime=250ms
  - Consumer started in multiplexed mode;  sleeps 1millis after processing each message
  - I trigger rebalances every 3-4s or so

- Deadlock
  - Both partition consumers are started by the sarama library 
  - Partition consumer blocks for a while and abandons subscription [link_1](https://github.com/Shopify/sarama/blob/master/consumer.go#L461) [link_2](https://github.com/Shopify/sarama/blob/master/consumer.go#L736) because upstream is slow
  - While its in this abandoned state, a rebalance is triggered
  - As part of rebalance, saramacluster.consumer.nextTick() calls release() to release all subs
  - Prior to the fix added by george (current master), this release() call will [block forever](https://github.com/bsm/sarama-cluster/blob/master/partitions.go#L267) 
  - After the fix added by george, Close() is replaced by AsyncClose(), so release() will finish, but then nextTick.subscribe() will fail with [this](https://github.com/Shopify/sarama/blob/master/consumer.go#L199) error. This goes on in a loop and will result in infinite rebalance errors

So, I see two issues now:
 - the message loss originally reported by this issue 
 - the deadlock which exist even before this fix

Whoever Owns Sarama: Verify if my analysis above is valid and update this ticket.

**Comment by danpmx** [comment] 2018-08-19 10:59
@georgeteo  our configuration:
`
conf := cluster.NewConfig()
conf.ChannelBufferSize = 1000
conf.Consumer.Return.Errors = true
conf.Group.Return.Notifications = true
conf.Group.Mode = cluster.ConsumerModePartitions
`

**Comment by imjustfly** [comment] 2018-08-23 14:48
@venkat1109 The `release()` call will not block, because  `sarama.PartitionConsumer.Close()` starts a goroutine to drain the `messages` channel. This is why a rebalance will lead to data loss.

  rebalance -> `release` -> `PartitionConsumer.Close()` -> drain `messages` -> data loss

**Comment by venkat1109** [comment] 2018-08-23 14:54
@imjustfly - sarama.PartitionConsumer.Close() will block because of this for range loop (and not because of drain, which runs in its own goroutine):
https://github.com/Shopify/sarama/blob/master/consumer.go#L431

i.e. sarama.PartitionConsumer.Close() will return only after child.errors channel is closed.

**Comment by imjustfly** [comment] 2018-08-23 16:01
@venkat1109 `child.errors` is closed:

  `Close()` -> `AyncClose()` -> `close(dying)` -> `close(trigger)` -> `close(feeder)` -> `close(errors)`

**Closed** 2019-06-18 00:11 UTC
